### PR TITLE
netcore

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**

### CODE REVIEW

**Comment by TonyValenti** [comment]
@VladislavAntonyuk Thanks so much for the commit!  I just merged it in.  How are you using WindowsInput?  I would love to know!

Do you have any experience setting up CI and such?  Would love to get some help to automate builds and publishing nuget packages.

**Comment by VladislavAntonyuk** [comment]
@TonyValenti I suggest you to use AppVeyor as CI. you can setup configuration and than export and commit yaml file.
I use WindowInput as a dependency of a plugin for my project Draw & GO

**Comment by TonyValenti** [comment]
Thanks!  I'll check it out!
Can I take a peek at Draw&Go?  Would love to see it in action.

**Comment by VladislavAntonyuk** [comment]
it is still in development. The video I recorded 3 years ago: https://www.youtube.com/watch?v=4YfLBOJTNaU and https://www.youtube.com/watch?v=Kla8w50jY3g

**Pull request merged**
